services:
  big-agi:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: [ "next", "start", "-p", "3000" ]
    environment:
      - PUPPETEER_WSS_ENDPOINT=ws://browserless:3000
      - PAGE_PASSWORD=R87uZmr!
    depends_on:
      - browserless

  browserless:
    image: browserless/chrome:latest
    ports:
      - "9222:3000"  # Map host's port 9222 to container's port 3000.
    environment:
      - MAX_CONCURRENT_SESSIONS=10