# Very simple docker-compose file to run the app on http://localhost:3000 (or http://127.0.0.1:3000).
#
# For more examples, such runnin big-AGI alongside a web browsing service, see the `docs/docker` folder.

services:
  big-agi:
    image: ghcr.io/enricoros/big-agi:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bigagi.entrypoints=http"
      - "traefik.http.routers.bigagi.rule=Host(`ai.aranaga.com`)"
      - "traefik.http.middlewares.bigagi-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bigagi.middlewares=bigagi-https-redirect"
      - "traefik.http.routers.bigagi-secure.entrypoints=https"
      - "traefik.http.routers.bigagi-secure.rule=Host(`ai.aranaga.com`)"
      - "traefik.http.routers.bigagi-secure.tls=true"
      - "traefik.http.routers.bigagi-secure.service=bigagi"
      - "traefik.http.services.bigagi.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

    command: [ "next", "start", "-p", "3000" ]

networks:
  proxy:
    external: true
