/**
 * This is here because the API does not provide a list of available upstream models, and does not provide
 * descriptions for the models.
 * (nor does it reliably provide context window sizes - upstream bug: https://github.com/ollama/ollama/issues/1473)
 *
 <<<
 Can you modify the following data structure, according to the updated information from the attached
 web page(https://ollama.ai/library?sort=featured). Be very thorough, do not skip any lines, both in
 the provided file and in the web page. Add/remove to reflect the order in the web page, update
 the *description* and *pulls*, and preserve the existing *added* field on existing entries, or set
 it to 20250312 on brand new entries. Note: the default contextWindow in code is 8192, so we do not redefine that.
 >>>
 */
export const OLLAMA_BASE_MODELS: { [key: string]: { description: string, pulls: number, contextWindow?: number, hasTools?: true, hasVision?: true, isEmbeddings?: true, tags?: string[], added?: string } } = {
  'qwq': { description: 'QwQ is the reasoning model of the Qwen series.', pulls: 866000, tags: ['32b'], hasTools: true, added: '20250312' },
  'deepseek-r1': { description: 'DeepSeek\'s first-generation of reasoning models with comparable performance to OpenAI-o1, including six dense models distilled from DeepSeek-R1 based on Llama and Qwen.', pulls: 25500000, tags: ['1.5b', '7b', '8b', '14b', '32b', '70b', '671b'], added: '20250128' },
  'llama3.3': { description: 'New state of the art 70B model. Llama 3.3 70B offers similar performance compared to the Llama 3.1 405B model.', pulls: 1500000, tags: ['70b'], hasTools: true, added: '20241210' },
  'phi4': { description: 'Phi-4 is a 14B parameter, state-of-the-art open model from Microsoft.', pulls: 1000000, tags: ['14b'], added: '20250128' },
  'llama3.2': { description: 'Meta\'s Llama 3.2 goes small with 1B and 3B models.', pulls: 10400000, tags: ['1b', '3b'], hasTools: true, added: '20241210' },
  'llama3.1': { description: 'Llama 3.1 is a new state-of-the-art model from Meta available in 8B, 70B and 405B parameter sizes.', pulls: 26700000, tags: ['8b', '70b', '405b'], hasTools: true, added: '20241210' },
  'nomic-embed-text': { description: 'A high-performing open embedding model with a large token context window.', pulls: 18700000, tags: [], isEmbeddings: true, added: '20240501' },
  'mistral': { description: 'The 7B model released by Mistral AI, updated to version 0.3.', pulls: 10200000, tags: ['7b'], hasTools: true },
  'llama3': { description: 'Meta Llama 3: The most capable openly available LLM to date', pulls: 7600000, tags: ['8b', '70b'], added: '20240501' },
  'qwen2.5': { description: 'Qwen2.5 models are pretrained on Alibaba\'s latest large-scale dataset, encompassing up to 18 trillion tokens. The model supports up to 128K tokens and has multilingual support.', pulls: 5200000, tags: ['0.5b', '1.5b', '3b', '7b', '14b', '32b', '72b'], hasTools: true, added: '20241210' },
  'qwen2.5-coder': { description: 'The latest series of Code-Specific Qwen models, with significant improvements in code generation, code reasoning, and code fixing.', pulls: 4500000, tags: ['0.5b', '1.5b', '3b', '7b', '14b', '32b'], hasTools: true, added: '20241210' },
  'qwen': { description: 'Qwen 1.5 is a series of large language models by Alibaba Cloud spanning from 0.5B to 110B parameters', pulls: 4500000, tags: ['0.5b', '1.8b', '4b', '7b', '14b', '32b', '72b', '110b'] },
  'gemma': { description: 'Gemma is a family of lightweight, state-of-the-art open models built by Google DeepMind. Updated to version 1.1', pulls: 4400000, tags: ['2b', '7b'], added: '20240501' },
  'qwen2': { description: 'Qwen2 is a new series of large language models from Alibaba group', pulls: 4100000, tags: ['0.5b', '1.5b', '7b', '72b'], hasTools: true, added: '20240628' },
  'llava': { description: '🌋 LLaVA is a novel end-to-end trained large multimodal model that combines a vision encoder and Vicuna for general-purpose visual and language understanding. Updated to version 1.6.', pulls: 4000000, tags: ['7b', '13b', '34b'], hasVision: true },
  'gemma2': { description: 'Google Gemma 2 is a high-performing and efficient model available in three sizes: 2B, 9B, and 27B.', pulls: 3400000, tags: ['2b', '9b', '27b'], added: '20240628' },
  'llama2': { description: 'Llama 2 is a collection of foundation language models ranging from 7B to 70B parameters.', pulls: 3000000, tags: ['7b', '13b', '70b'] },
  'phi3': { description: 'Phi-3 is a family of lightweight 3B (Mini) and 14B (Medium) state-of-the-art open models by Microsoft.', pulls: 2900000, tags: ['3.8b', '14b'], added: '20240501' },
  'codellama': { description: 'A large language model that can use text prompts to generate and discuss code.', pulls: 1800000, tags: ['7b', '13b', '34b', '70b'] },
  'mxbai-embed-large': { description: 'State-of-the-art large embedding model from mixedbread.ai', pulls: 1700000, tags: ['335m'], isEmbeddings: true, added: '20240501' },
  'llama3.2-vision': { description: 'Llama 3.2 Vision is a collection of instruction-tuned image reasoning generative models in 11B and 90B sizes.', pulls: 1500000, tags: ['11b', '90b'], hasVision: true, added: '20241210' },
  'tinyllama': { description: 'The TinyLlama project is an open endeavor to train a compact 1.1B Llama model on 3 trillion tokens.', pulls: 1300000, tags: ['1.1b'] },
  'mistral-nemo': { description: 'A state-of-the-art 12B model with 128k context length, built by Mistral AI in collaboration with NVIDIA.', pulls: 1300000, tags: ['12b'], hasTools: true, added: '20241210' },
  'starcoder2': { description: 'StarCoder2 is the next generation of transparently trained open code LLMs that comes in three sizes: 3B, 7B and 15B parameters.', pulls: 897600, tags: ['3b', '7b', '15b'], added: '20240501' },
  'deepseek-v3': { description: 'A strong Mixture-of-Experts (MoE) language model with 671B total parameters with 37B activated for each token.', pulls: 748300, tags: ['671b'], added: '20250128' },
  'llama2-uncensored': { description: 'Uncensored Llama 2 model by George Sung and Jarrad Hope.', pulls: 728100, tags: ['7b', '70b'] },
  'deepseek-coder-v2': { description: 'An open-source Mixture-of-Experts code language model that achieves performance comparable to GPT4-Turbo in code-specific tasks.', pulls: 722000, tags: ['16b', '236b'], added: '20240628' },
  'snowflake-arctic-embed': { description: 'A suite of text embedding models by Snowflake, optimized for performance.', pulls: 697600, tags: ['22m', '33m', '110m', '137m', '335m'], isEmbeddings: true, added: '20240501' },
  'deepseek-coder': { description: 'DeepSeek Coder is a capable coding model trained on two trillion code and natural language tokens.', pulls: 601200, tags: ['1.3b', '6.7b', '33b'] },
  'mixtral': { description: 'A set of Mixture of Experts (MoE) model with open weights by Mistral AI in 8x7b and 8x22b parameter sizes.', pulls: 582600, tags: ['8x7b', '8x22b'], hasTools: true, added: '20250312' },
  'bge-m3': { description: 'BGE-M3 is a new model from BAAI distinguished for its versatility in Multi-Functionality, Multi-Linguality, and Multi-Granularity.', pulls: 555500, tags: ['567m'], isEmbeddings: true, added: '20241210' },
  'minicpm-v': { description: 'A series of multimodal LLMs (MLLMs) designed for vision-language understanding.', pulls: 535600, tags: ['8b'], hasVision: true, added: '20241210' },
  'codegemma': { description: 'CodeGemma is a collection of powerful, lightweight models that can perform a variety of coding tasks like fill-in-the-middle code completion, code generation, natural language understanding, mathematical reasoning, and instruction following.', pulls: 530400, tags: ['2b', '7b'], added: '20240501' },
  'dolphin-mixtral': { description: 'Uncensored, 8x7b and 8x22b fine-tuned models based on the Mixtral mixture of experts models that excels at coding tasks. Created by Eric Hartford.', pulls: 522200, tags: ['8x7b', '8x22b'], added: '20250312' },
  'openthinker': { description: 'A fully open-source family of reasoning models built using a dataset derived by distilling DeepSeek-R1.', pulls: 509700, tags: ['7b', '32b'], added: '20250219' },
  'phi': { description: 'Phi-2: a 2.7B language model by Microsoft Research that demonstrates outstanding reasoning and language understanding capabilities.', pulls: 496900, tags: ['2.7b'] },
  'llava-llama3': { description: 'A LLaVA model fine-tuned from Llama 3 Instruct with better scores in several benchmarks.', pulls: 448000, tags: ['8b'], hasVision: true, added: '20240628' },
  'dolphin3': { description: 'Dolphin 3.0 Llama 3.1 8B 🐬 is the next generation of the Dolphin series of instruct-tuned models designed to be the ultimate general purpose local model, enabling coding, math, agentic, function calling, and general use cases.', pulls: 386700, tags: ['8b'], added: '20250128' },
  'smollm2': { description: 'SmolLM2 is a family of compact language models available in three size: 135M, 360M, and 1.7B parameters.', pulls: 370800, tags: ['135m', '360m', '1.7b'], hasTools: true, added: '20241210' },
  'wizardlm2': { description: 'State of the art large language model from Microsoft AI with improved performance on complex chat, multilingual, reasoning and agent use cases.', pulls: 356800, tags: ['7b', '8x22b'], added: '20240501' },
  'olmo2': { description: 'OLMo 2 is a new family of 7B and 13B models trained on up to 5T tokens. These models are on par with or better than equivalently sized fully open models, and competitive with open-weight models such as Llama 3.1 on English academic benchmarks.', pulls: 352600, tags: ['7b', '13b'], added: '20250312' },
  'dolphin-mistral': { description: 'The uncensored Dolphin model based on Mistral that excels at coding tasks. Updated to version 2.8.', pulls: 325900, tags: ['7b'] },
  'all-minilm': { description: 'Embedding models on very large sentence level datasets.', pulls: 311500, tags: ['22m', '33m'], isEmbeddings: true, added: '20240501' },
  'mistral-small': { description: 'Mistral Small 3 sets a new benchmark in the "small" Large Language Models category below 70B.', pulls: 297800, tags: ['22b', '24b'], hasTools: true, added: '20250219' },
  'dolphin-llama3': { description: 'Dolphin 2.9 is a new model with 8B and 70B sizes by Eric Hartford based on Llama 3 that has a variety of instruction, conversational, and coding skills.', pulls: 293500, tags: ['8b', '70b'], added: '20240501' },
  'command-r': { description: 'Command R is a Large Language Model optimized for conversational interaction and long context tasks.', pulls: 283000, tags: ['35b'], hasTools: true, added: '20240501' },
  'orca-mini': { description: 'A general-purpose model ranging from 3 billion parameters to 70 billion, suitable for entry-level hardware.', pulls: 277300, tags: ['3b', '7b', '13b', '70b'] },
  'yi': { description: 'Yi 1.5 is a high-performing, bilingual language model.', pulls: 267300, tags: ['6b', '9b', '34b'] },
  'hermes3': { description: 'Hermes 3 is the latest version of the flagship Hermes series of LLMs by Nous Research', pulls: 264700, tags: ['3b', '8b', '70b', '405b'], hasTools: true, added: '20241210' },
  'phi3.5': { description: 'A lightweight AI model with 3.8 billion parameters with performance overtaking similarly and larger sized models.', pulls: 249900, tags: ['3.8b'], added: '20241210' },
  'zephyr': { description: 'Zephyr is a series of fine-tuned versions of the Mistral and Mixtral models that are trained to act as helpful assistants.', pulls: 238300, tags: ['7b', '141b'] },
  'codestral': { description: 'Codestral is Mistral AI\'s first-ever code model designed for code generation tasks.', pulls: 227900, tags: ['22b'], added: '20240628' },
  'granite-code': { description: 'A family of open foundation models by IBM for Code Intelligence', pulls: 191500, tags: ['3b', '8b', '20b', '34b'], added: '20240628' },
  'smollm': { description: '🪐 A family of small models with 135M, 360M, and 1.7B parameters, trained on a new high-quality dataset.', pulls: 188100, tags: ['135m', '360m', '1.7b'], added: '20241210' },
  'starcoder': { description: 'StarCoder is a code generation model trained on 80+ programming languages.', pulls: 187700, tags: ['1b', '3b', '7b', '15b'] },
  'wizard-vicuna-uncensored': { description: 'Wizard Vicuna Uncensored is a 7B, 13B, and 30B parameter model based on Llama 2 uncensored by Eric Hartford.', pulls: 185800, tags: ['7b', '13b', '30b'] },
  'vicuna': { description: 'General use chat model based on Llama and Llama 2 with 2K to 16K context sizes.', pulls: 176200, tags: ['7b', '13b', '33b'] },
  'mistral-openorca': { description: 'Mistral OpenOrca is a 7 billion parameter model, fine-tuned on top of the Mistral 7B model using the OpenOrca dataset.', pulls: 167100, tags: ['7b'] },
  'llama2-chinese': { description: 'Llama 2 based model fine tuned to improve Chinese dialogue ability.', pulls: 149900, tags: ['7b', '13b'] },
  'openchat': { description: 'A family of open-source models trained on a wide variety of data, surpassing ChatGPT on various benchmarks. Updated to version 3.5-0106.', pulls: 145400, tags: ['7b'] },
  'codegeex4': { description: 'A versatile model for AI software development scenarios, including code completion.', pulls: 139200, tags: ['9b'], added: '20241210' },
  'aya': { description: 'Aya 23, released by Cohere, is a new family of state-of-the-art, multilingual models that support 23 languages.', pulls: 136400, tags: ['8b', '35b'], added: '20240628' },
  'codeqwen': { description: 'CodeQwen1.5 is a large language model pretrained on a large amount of code data.', pulls: 132300, tags: ['7b'], added: '20240501' },
  'deepseek-llm': { description: 'An advanced language model crafted with 2 trillion bilingual tokens.', pulls: 132100, tags: ['7b', '67b'] },
  'deepseek-v2': { description: 'A strong, economical, and efficient Mixture-of-Experts language model.', pulls: 128300, tags: ['16b', '236b'], added: '20240628' },
  'mistral-large': { description: 'Mistral Large 2 is Mistral\'s new flagship model that is significantly more capable in code generation, mathematics, and reasoning with 128k context window and support for dozens of languages.', pulls: 125100, tags: ['123b'], hasTools: true, added: '20241210' },
  'glm4': { description: 'A strong multi-lingual general language model with competitive performance to Llama 3.', pulls: 123500, tags: ['9b'], added: '20241210' },
  'stable-code': { description: 'Stable Code 3B is a coding model with instruct and code completion variants on par with models such as Code Llama 7B that are 2.5x larger.', pulls: 122400, tags: ['3b'] },
  'openhermes': { description: 'OpenHermes 2.5 is a 7B model fine-tuned by Teknium on Mistral with fully open datasets.', pulls: 122000, tags: [] },
  'nous-hermes2': { description: 'The powerful family of models by Nous Research that excels at scientific discussion and coding tasks.', pulls: 121900, tags: ['10.7b', '34b'] },
  'qwen2-math': { description: 'Qwen2 Math is a series of specialized math language models built upon the Qwen2 LLMs, which significantly outperforms the mathematical capabilities of open-source models and even closed-source models (e.g., GPT4o).', pulls: 120600, tags: ['1.5b', '7b', '72b'], added: '20241210' },
  'tinydolphin': { description: 'An experimental 1.1B parameter model trained on the new Dolphin 2.8 dataset by Eric Hartford and based on TinyLlama.', pulls: 120500, tags: ['1.1b'] },
  'command-r-plus': { description: 'Command R+ is a powerful, scalable large language model purpose-built to excel at real-world enterprise use cases.', pulls: 119700, contextWindow: 128000, tags: ['104b'], hasTools: true, added: '20240501' },
  'wizardcoder': { description: 'State-of-the-art code generation model', pulls: 117200, tags: ['33b'] },
  'moondream': { description: 'moondream2 is a small vision language model designed to run efficiently on edge devices.', pulls: 116900, tags: ['1.8b'], hasVision: true, added: '20240501' },
  'bakllava': { description: 'BakLLaVA is a multimodal model consisting of the Mistral 7B base model augmented with the LLaVA architecture.', pulls: 109700, tags: ['7b'], hasVision: true },
  'stablelm2': { description: 'Stable LM 2 is a state-of-the-art 1.6B and 12B parameter language model trained on multilingual data in English, Spanish, German, Italian, French, Portuguese, and Dutch.', pulls: 108100, tags: ['1.6b', '12b'] },
  'neural-chat': { description: 'A fine-tuned model based on Mistral with good coverage of domain and language.', pulls: 104700, tags: ['7b'] },
  'reflection': { description: 'A high-performing model trained with a new technique called Reflection-tuning that teaches a LLM to detect mistakes in its reasoning and correct course.', pulls: 103400, tags: ['70b'], added: '20241210' },
  'wizard-math': { description: 'Model focused on math and logic problems', pulls: 101100, tags: ['7b', '13b', '70b'] },
  'llama3-gradient': { description: 'This model extends LLama-3 8B\'s context length from 8k to over 1m tokens.', pulls: 98100, tags: ['8b', '70b'], added: '20240501' },
  'llama3-chatqa': { description: 'A model from NVIDIA based on Llama 3 that excels at conversational question answering (QA) and retrieval-augmented generation (RAG).', pulls: 97200, tags: ['8b', '70b'], added: '20240628' },
  'sqlcoder': { description: 'SQLCoder is a code completion model fined-tuned on StarCoder for SQL generation tasks', pulls: 93700, tags: ['7b', '15b'] },
  'samantha-mistral': { description: 'A companion assistant trained in philosophy, psychology, and personal relationships. Based on Mistral.', pulls: 90100, tags: ['7b'] },
  'bge-large': { description: 'Embedding model from BAAI mapping texts to vectors.', pulls: 89700, tags: ['335m'], isEmbeddings: true, added: '20241210' },
  'xwinlm': { description: 'Conversational model based on Llama 2 that performs competitively on various benchmarks.', pulls: 84400, tags: ['7b', '13b'] },
  'dolphincoder': { description: 'A 7B and 15B uncensored variant of the Dolphin model family that excels at coding, based on StarCoder2.', pulls: 84200, tags: ['7b', '15b'], added: '20240501' },
  'nous-hermes': { description: 'General use models based on Llama and Llama 2 from Nous Research.', pulls: 82300, tags: ['7b', '13b'] },
  'granite3.1-dense': { description: 'The IBM Granite 2B and 8B models are text-only dense LLMs trained on over 12 trillion tokens of data, demonstrated significant improvements over their predecessors in performance and speed in IBM\'s initial testing.', pulls: 81800, tags: ['2b', '8b'], hasTools: true, added: '20250128' },
  'llava-phi3': { description: 'A new small LLaVA model fine-tuned from Phi 3 Mini.', pulls: 81700, tags: ['3.8b'], hasVision: true, added: '20240628' },
  'phind-codellama': { description: 'Code generation model based on Code Llama.', pulls: 81500, tags: ['34b'] },
  'starling-lm': { description: 'Starling is a large language model trained by reinforcement learning from AI feedback focused on improving chatbot helpfulness.', pulls: 81300, tags: ['7b'] },
  'solar': { description: 'A compact, yet powerful 10.7B large language model designed for single-turn conversation.', pulls: 79100, tags: ['10.7b'] },
  'yarn-llama2': { description: 'An extension of Llama 2 that supports a context of up to 128k tokens.', pulls: 78900, contextWindow: 128000, tags: ['7b', '13b'] },
  'yi-coder': { description: 'Yi-Coder is a series of open-source code language models that delivers state-of-the-art coding performance with fewer than 10 billion parameters.', pulls: 77000, tags: ['1.5b', '9b'], added: '20241210' },
  'athene-v2': { description: 'Athene-V2 is a 72B parameter model which excels at code completion, mathematics, and log extraction tasks.', pulls: 76900, tags: ['72b'], hasTools: true, added: '20241210' },
  'wizardlm': { description: 'General use model based on Llama 2.', pulls: 75800, tags: [] },
  'internlm2': { description: 'InternLM2.5 is a 7B parameter model tailored for practical scenarios with outstanding reasoning capability.', pulls: 74100, tags: ['1m', '1.8b', '7b', '20b'], added: '20241210' },
  'falcon': { description: 'A large language model built by the Technology Innovation Institute (TII) for use in summarization, text generation, and chat bots.', pulls: 70100, tags: ['7b', '40b', '180b'] },
  'nemotron-mini': { description: 'A commercial-friendly small language model by NVIDIA optimized for roleplay, RAG QA, and function calling.', pulls: 69900, tags: ['4b'], hasTools: true, added: '20241210' },
  'nemotron': { description: 'Llama-3.1-Nemotron-70B-Instruct is a large language model customized by NVIDIA to improve the helpfulness of LLM generated responses to user queries.', pulls: 66900, tags: ['70b'], hasTools: true, added: '20241210' },
  'deepscaler': { description: 'A fine-tuned version of Deepseek-R1-Distilled-Qwen-1.5B that surpasses the performance of OpenAI\'s o1-preview with just 1.5B parameters on popular math evaluations.', pulls: 66200, tags: ['1.5b'], added: '20250219' },
  'dolphin-phi': { description: '2.7B uncensored Dolphin model by Eric Hartford, based on the Phi language model by Microsoft Research.', pulls: 65900, tags: ['2.7b'] },
  'orca2': { description: 'Orca 2 is built by Microsoft research, and are a fine-tuned version of Meta\'s Llama 2 models. The model is designed to excel particularly in reasoning.', pulls: 63800, tags: ['7b', '13b'] },
  'wizardlm-uncensored': { description: 'Uncensored version of Wizard LM model', pulls: 60900, tags: ['13b'] },
  'stable-beluga': { description: 'Llama 2 based model fine tuned on an Orca-style dataset. Originally called Free Willy.', pulls: 59000, tags: ['7b', '13b', '70b'] },
  'granite3-dense': { description: 'The IBM Granite 2B and 8B models are designed to support tool-based use cases and support for retrieval augmented generation (RAG), streamlining code generation, translation and bug fixing.', pulls: 57900, tags: ['2b', '8b'], hasTools: true, added: '20241210' },
  'llama3-groq-tool-use': { description: 'A series of models from Groq that represent a significant advancement in open-source AI capabilities for tool use/function calling.', pulls: 56100, tags: ['8b', '70b'], hasTools: true, added: '20240628' },
  'paraphrase-multilingual': { description: 'Sentence-transformers model that can be used for tasks like clustering or semantic search.', pulls: 53000, tags: ['278m'], isEmbeddings: true, added: '20241210' },
  'deepseek-v2.5': { description: 'An upgraded version of DeekSeek-V2 that integrates the general and coding abilities of both DeepSeek-V2-Chat and DeepSeek-Coder-V2-Instruct.', pulls: 49900, tags: ['236b'], added: '20241210' },
  'smallthinker': { description: 'A new small reasoning model fine-tuned from the Qwen 2.5 3B Instruct model.', pulls: 48000, tags: ['3b'], added: '20241210' },
  'medllama2': { description: 'Fine-tuned Llama 2 model to answer medical questions based on an open source medical dataset.', pulls: 47700, tags: ['7b'] },
  'meditron': { description: 'Open-source medical large language model adapted from Llama 2 to the medical domain.', pulls: 47600, tags: ['7b', '70b'] },
  'aya-expanse': { description: 'Cohere For AI\'s language models trained to perform well across 23 different languages.', pulls: 46600, tags: ['8b', '32b'], hasTools: true, added: '20241210' },
  'llama-pro': { description: 'An expansion of Llama 2 that specializes in integrating both general language understanding and domain-specific knowledge, particularly in programming and mathematics.', pulls: 45700, tags: [] },
  'yarn-mistral': { description: 'An extension of Mistral to support context windows of 64K or 128K.', pulls: 45200, tags: ['7b'] },
  'granite3-moe': { description: 'The IBM Granite 1B and 3B models are the first mixture of experts (MoE) Granite models from IBM designed for low latency usage.', pulls: 44300, tags: ['1b', '3b'], hasTools: true, added: '20241210' },
  'falcon3': { description: 'A family of efficient AI models under 10B parameters performant in science, math, and coding through innovative training techniques.', pulls: 42200, tags: ['1b', '3b', '7b', '10b'], added: '20241210' },
  'nexusraven': { description: 'Nexus Raven is a 13B instruction tuned model for function calling tasks.', pulls: 41700, tags: ['13b'] },
  'codeup': { description: 'Great code generation model based on Llama2.', pulls: 39700, tags: ['13b'] },
  'everythinglm': { description: 'Uncensored Llama2 based model with support for a 16K context window.', pulls: 38500, tags: ['13b'] },
  'nous-hermes2-mixtral': { description: 'The Nous Hermes 2 model from Nous Research, now trained over Mixtral.', pulls: 38400, tags: ['8x7b'], added: '20241210' },
  'snowflake-arctic-embed2': { description: 'Snowflake\'s frontier embedding model. Arctic Embed 2.0 adds multilingual support without sacrificing English performance or scalability.', pulls: 37100, tags: ['568m'], isEmbeddings: true, added: '20241210' },
  'shieldgemma': { description: 'ShieldGemma is set of instruction tuned models for evaluating the safety of text prompt input and text output responses against a set of defined safety policies.', pulls: 36100, tags: ['2b', '9b', '27b'], added: '20241210' },
  'granite3.1-moe': { description: 'The IBM Granite 1B and 3B models are long-context mixture of experts (MoE) Granite models from IBM designed for low latency usage.', pulls: 35500, tags: ['1b', '3b'], hasTools: true, added: '20250128' },
  'marco-o1': { description: 'An open large reasoning model for real-world solutions by the Alibaba International Digital Commerce Group (AIDC-AI).', pulls: 33300, tags: ['7b'], added: '20241210' },
  'mathstral': { description: 'MathΣtral: a 7B model designed for math reasoning and scientific discovery by Mistral AI.', pulls: 32700, tags: ['7b'], added: '20241210' },
  'reader-lm': { description: 'A series of models that convert HTML content to Markdown content, which is useful for content conversion tasks.', pulls: 32500, tags: ['0.5b', '1.5b'], added: '20241210' },
  'falcon2': { description: 'Falcon2 is an 11B parameters causal decoder-only model built by TII and trained over 5T tokens.', pulls: 32300, tags: ['11b'] },
  'magicoder': { description: '🎩 Magicoder is a family of 7B parameter models trained on 75K synthetic instruction data using OSS-Instruct, a novel approach to enlightening LLMs with open-source code snippets.', pulls: 32200, tags: ['7b'] },
  'stablelm-zephyr': { description: 'A lightweight chat model allowing accurate, and responsive output without requiring high-end hardware.', pulls: 32100, tags: ['3b'] },
  'solar-pro': { description: 'Solar Pro Preview: an advanced large language model (LLM) with 22 billion parameters designed to fit into a single GPU', pulls: 32100, tags: ['22b'], added: '20241210' },
  'phi4-mini': { description: 'Phi-4-mini brings significant enhancements in multilingual support, reasoning, and mathematics, and now, the long-awaited function calling feature is finally supported.', pulls: 31900, tags: ['3.8b'], hasTools: true, added: '20250312' },
  'codebooga': { description: 'A high-performing code instruct model created by merging two existing code models.', pulls: 31400, tags: ['34b'] },
  'llama-guard3': { description: 'Llama Guard 3 is a series of models fine-tuned for content safety classification of LLM inputs and responses.', pulls: 30600, tags: ['1b', '8b'], added: '20241210' },
  'duckdb-nsql': { description: '7B parameter text-to-SQL model made by MotherDuck and Numbers Station.', pulls: 30500, tags: ['7b'] },
  'mistrallite': { description: 'MistralLite is a fine-tuned model based on Mistral with enhanced capabilities of processing long contexts.', pulls: 30100, tags: ['7b'] },
  'wizard-vicuna': { description: 'Wizard Vicuna is a 13B parameter model based on Llama 2 trained by MelodysDreamj.', pulls: 29600, tags: ['13b'] },
  'exaone3.5': { description: 'EXAONE 3.5 is a collection of instruction-tuned bilingual (English and Korean) generative models ranging from 2.4B to 32B parameters, developed and released by LG AI Research.', pulls: 29100, tags: ['2.4b', '7.8b', '32b'], added: '20241210' },
  'nuextract': { description: 'A 3.8B model fine-tuned on a private high-quality synthetic dataset for information extraction, based on Phi-3.', pulls: 26400, tags: ['3.8b'], added: '20241210' },
  'opencoder': { description: 'OpenCoder is an open and reproducible code LLM family which includes 1.5B and 8B models, supporting chat in English and Chinese languages.', pulls: 26100, tags: ['1.5b', '8b'], added: '20241210' },
  'megadolphin': { description: 'MegaDolphin-2.2-120b is a transformation of Dolphin-2.2-70b created by interleaving the model with itself.', pulls: 25300, tags: ['120b'] },
  'command-r7b': { description: 'The smallest model in Cohere\'s R series delivers top-tier speed, efficiency, and quality to build powerful AI applications on commodity GPUs and edge devices.', pulls: 24500, tags: ['7b'], hasTools: true, added: '20250312' },
  'notux': { description: 'A top-performing mixture of experts model, fine-tuned with high-quality data.', pulls: 24400, tags: ['8x7b'] },
  'open-orca-platypus2': { description: 'Merge of the Open Orca OpenChat model and the Garage-bAInd Platypus 2 model. Designed for chat and code generation.', pulls: 23900, tags: ['13b'] },
  'notus': { description: 'A 7B chat model fine-tuned with high-quality data and based on Zephyr.', pulls: 23700, tags: ['7b'] },
  'goliath': { description: 'A language model created by combining two fine-tuned Llama 2 70B models into one.', pulls: 23000, tags: [] },
  'bespoke-minicheck': { description: 'A state-of-the-art fact-checking model developed by Bespoke Labs.', pulls: 22700, tags: ['7b'], added: '20241210' },
  'granite-embedding': { description: 'The IBM Granite Embedding 30M and 278M models models are text-only dense biencoder embedding models, with 30M available in English only and 278M serving multilingual use cases.', pulls: 21300, tags: ['30m', '278m'], isEmbeddings: true, added: '20241210' },
  'tulu3': { description: 'Tülu 3 is a leading instruction following model family, offering fully open-source data, code, and recipes by the The Allen Institute for AI.', pulls: 20200, tags: ['8b', '70b'], added: '20241210' },
  'granite3.2-vision': { description: 'A compact and efficient vision-language model, specifically designed for visual document understanding, enabling automated content extraction from tables, charts, infographics, plots, diagrams, and more.', pulls: 19100, tags: ['2b'], hasVision: true, hasTools: true, added: '20250312' },
  'firefunction-v2': { description: 'An open weights function calling model based on Llama 3, competitive with GPT-4o function calling capabilities.', pulls: 19000, tags: ['70b'], hasTools: true, added: '20241210' },
  'dbrx': { description: 'DBRX is an open, general-purpose LLM created by Databricks.', pulls: 18400, tags: ['132b'], added: '20241210' },
  'granite3.2': { description: 'Granite-3.2 is a family of long-context AI models from IBM Granite fine-tuned for thinking capabilities.', pulls: 16900, tags: ['2b', '8b'], hasTools: true, added: '20250312' },
  'granite3-guardian': { description: 'The IBM Granite Guardian 3.0 2B and 8B models are designed to detect risks in prompts and/or responses.', pulls: 16600, tags: ['2b', '8b'], added: '20241210' },
  'r1-1776': { description: 'A version of the DeepSeek-R1 model that has been post trained to provide unbiased, accurate, and factual information by Perplexity.', pulls: 16100, tags: ['70b', '671b'], added: '20250312' },
  'alfred': { description: 'A robust conversational model designed to be used for both chat and instruct use cases.', pulls: 15900, tags: ['40b'] },
  'sailor2': { description: 'Sailor2 are multilingual language models made for South-East Asia. Available in 1B, 8B, and 20B parameter sizes.', pulls: 9788, tags: ['1b', '8b', '20b'], added: '20241210' },
  'gemma3': { description: 'The current strongest model that fits on a single GPU.', pulls: 6711, tags: ['1b', '4b', '12b', '27b'], added: '20250312' },
  'command-r7b-arabic': { description: 'A new state-of-the-art version of the lightweight Command R7B model that excels in advanced Arabic language capabilities for enterprises in the Middle East and Northern Africa.', pulls: 3347, tags: ['7b'], hasTools: true, added: '20250312' },
  // NOTE: we had older/low-pull models here, but they are not in the list anymore, as it's noise. We removed around 45 of those.
};
// export const OLLAMA_LAST_UPDATE: string = '20250312';
export const OLLAMA_PREV_UPDATE: string = '20250219';