import type { RenderBlockInputs } from './blocks.types';
import { heuristicAllMarkdownImageReferences } from './image/RenderImageURL';
import { heuristicIsBlockPureHTML } from './danger-html/RenderDangerousHtml';
import { countLines } from '~/common/util/textUtils';


export function parseBlocksFromText(text: string): RenderBlockInputs {

  // special case: this could be generated by a proxy that returns an HTML page instead of the API response
  if (heuristicIsBlockPureHTML(text))
    return [{ bkt: 'dang-html-bk', html: text }];

  // special case: markdown image references (e.g., ![alt text](https://example.com/image.png))
  const imageBkInputs = heuristicAllMarkdownImageReferences(text);
  if (imageBkInputs)
    return imageBkInputs;

  // Phase 1: Parse fenced code blocks with stack-based state tracking
  const phase1Blocks = _parseFencedBlocks(text);

  // Phase 2: Extract HTML/SVG blocks from markdown segments
  const blocks: RenderBlockInputs = [];
  for (const block of phase1Blocks) {
    if (block.bkt === 'md-bk')
      _extractHtmlSvgBlocks(block.content, blocks);
    else
      blocks.push(block);
  }

  return blocks;
}


// Fence line detection: matches lines starting with 3+ backticks or tildes
const _fenceLineRegex = /^(`{3,}|~{3,})(.*)/;

/**
 * Phase 1: Line-by-line stateful parser with stack-based fence depth tracking.
 *
 * Classification of fence lines:
 * - FENCE_INFO (```python):  single-word after fence → always an opening signal
 * - FENCE_PURE (```):        only whitespace after fence → close at depth > 0, open at depth 0
 * - FENCE_DIRTY (```Text..): multi-word after fence → dirty close at depth > 0, plain text at depth 0
 *
 * Stack rules:
 * - Openings push {char, len} onto the stack
 * - Closes pop if fence char and length (≥ opening) match the top of stack
 * - Only level-0 blocks are emitted; nested fences become content of the outer block
 */
function _parseFencedBlocks(text: string): RenderBlockInputs {
  const lines = text.split('\n');
  const blocks: RenderBlockInputs = [];

  // Stack of open fence blocks: each entry tracks the fence character and length
  const stack: { fenceChar: string; fenceLen: number }[] = [];

  // Accumulation buffers
  let mdLines: string[] = [];   // markdown text lines (depth 0)
  let codeLines: string[] = []; // code content lines (depth > 0)
  let codeTitle = '';            // info string of the outermost code block

  // Flush accumulated markdown lines as a md-bk block
  const flushMarkdown = () => {
    if (mdLines.length > 0) {
      const content = mdLines.join('\n');
      if (content)
        blocks.push({ bkt: 'md-bk', content });
      mdLines = [];
    }
  };

  // Emit a code-bk block from accumulated code lines
  const emitCodeBlock = (isPartial: boolean) => {
    // Trim trailing whitespace-only characters from the last line, preserving leading spaces
    let code = codeLines.join('\n');
    code = code.replace(/[\t ]+$/, '');
    blocks.push({
      bkt: 'code-bk',
      title: codeTitle,
      code,
      lines: countLines(code),
      isPartial,
    });
    codeLines = [];
    codeTitle = '';
  };

  for (const line of lines) {
    const depth = stack.length;
    const fenceMatch = line.match(_fenceLineRegex);

    if (depth === 0) {
      // --- At top level: looking for code block openings ---
      if (fenceMatch) {
        const fenceStr = fenceMatch[1];
        const afterFence = fenceMatch[2].trim();
        // Single non-whitespace token = info string (language tag); empty = pure fence
        const isSingleToken = afterFence !== '' && !/\s/.test(afterFence);

        if (afterFence === '' || isSingleToken) {
          // Opening fence: flush any preceding markdown and start a code block
          flushMarkdown();
          stack.push({ fenceChar: fenceStr[0], fenceLen: fenceStr.length });
          codeTitle = afterFence;
          codeLines = [];
        } else {
          // Multi-word text after backticks at depth 0 → not a fence, just markdown
          mdLines.push(line);
        }
      } else {
        mdLines.push(line);
      }
    } else {
      // --- Inside a code block: looking for closes or nested opens ---
      if (fenceMatch) {
        const fenceStr = fenceMatch[1];
        const fenceChar = fenceStr[0];
        const fenceLen = fenceStr.length;
        const afterFence = fenceMatch[2].trim();
        const isSingleToken = afterFence !== '' && !/\s/.test(afterFence);
        const top = stack[stack.length - 1];

        if (isSingleToken) {
          // Single-word info string → nested opening (e.g., ```json inside ```markdown)
          // Track depth so the outer block absorbs this content
          stack.push({ fenceChar, fenceLen });
          codeLines.push(line);
        } else if (fenceChar === top.fenceChar && fenceLen >= top.fenceLen) {
          // Fence matches the top of stack → close attempt (pure or dirty)
          stack.pop();
          if (stack.length === 0) {
            // Back to depth 0: emit the code block
            emitCodeBlock(false);
            // For dirty closes, trailing text becomes the start of the next markdown block
            if (afterFence)
              mdLines.push(afterFence);
          } else {
            // Still nested: this closing fence is content of the outer block
            codeLines.push(line);
          }
        } else {
          // Fence doesn't match top of stack (wrong char or too short) → just content
          codeLines.push(line);
        }
      } else {
        // Regular text line inside code block
        codeLines.push(line);
      }
    }
  }

  // End of text: flush remaining state
  if (stack.length > 0)
    emitCodeBlock(true);
  flushMarkdown();

  return blocks;
}


/**
 * Phase 2: Extract HTML document and SVG blocks from markdown text segments.
 * Splits a markdown text into sub-blocks, extracting `<!DOCTYPE html>...</html>`
 * and `<svg ...>...</svg>` as code-bk blocks.
 */
function _extractHtmlSvgBlocks(text: string, blocks: RenderBlockInputs): void {
  const regexPatterns = {
    htmlCodeBlock: /<!DOCTYPE html>([\s\S]*?)<\/html>/gi,
    svgBlock: /<svg (xmlns|width|viewBox)=([\s\S]*?)<\/svg>/g,
  };

  let lastIndex = 0;

  while (true) {

    // Find the earliest match across all patterns
    let match: RegExpExecArray | null = null;
    let matchType: keyof typeof regexPatterns | null = null;
    let earliestMatchIndex: number | null = null;

    for (const type in regexPatterns) {
      const regex = regexPatterns[type as keyof typeof regexPatterns];
      regex.lastIndex = lastIndex;
      const currentMatch = regex.exec(text);
      if (currentMatch && (earliestMatchIndex === null || currentMatch.index < earliestMatchIndex)) {
        match = currentMatch;
        matchType = type as keyof typeof regexPatterns;
        earliestMatchIndex = currentMatch.index;
      }
    }
    if (match === null)
      break;

    // Text before the match
    if (match.index > lastIndex)
      blocks.push({ bkt: 'md-bk', content: text.slice(lastIndex, match.index) });

    // Emit the matched block
    switch (matchType) {
      case 'htmlCodeBlock':
        const preMatchHtml: string = `<!DOCTYPE html>${match[1]}</html>`;
        blocks.push({ bkt: 'code-bk', title: 'html', code: preMatchHtml, lines: countLines(preMatchHtml), isPartial: false });
        break;

      case 'svgBlock':
        blocks.push({ bkt: 'code-bk', title: 'svg', code: match[0], lines: countLines(match[0]), isPartial: false });
        break;
    }

    lastIndex = match.index + match[0].length;
  }

  // Remainder (or entire text if no matches) is markdown text
  if (lastIndex < text.length)
    blocks.push({ bkt: 'md-bk', content: text.slice(lastIndex) });
}
