import { Box, Typography, CssVarsProvider } from '@mui/joy';
import { useRouter } from 'next/navigation';

const CustomTypography = ({ children, ...props }: { children: React.ReactNode; [key: string]: any }) => (
  <Typography color="primary" {...props}>
    {children}
  </Typography>
);

export default function TermsOfService() {
  const router = useRouter();
  return (
    <CssVarsProvider>
      <Box
        sx={{
          minHeight: '100vh',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'flex-start',
          paddingX: '20%',
          color: '#fff',
          background: `radial-gradient(circle at 84% 82%, rgba(217, 217, 217,0.03) 0%, rgba(217, 217, 217,0.03) 21%,transparent 21%, transparent 100%),radial-gradient(circle at 75% 56%, rgba(3, 3, 3,0.03) 0%, rgba(3, 3, 3,0.03) 30%,transparent 30%, transparent 100%),radial-gradient(circle at 74% 53%, rgba(153, 153, 153,0.03) 0%, rgba(153, 153, 153,0.03) 95%,transparent 95%, transparent 100%),radial-gradient(circle at 86% 43%, rgba(209, 209, 209,0.03) 0%, rgba(209, 209, 209,0.03) 83%,transparent 83%, transparent 100%),radial-gradient(circle at 64% 88%, rgba(192, 192, 192,0.03) 0%, rgba(192, 192, 192,0.03) 2%,transparent 2%, transparent 100%),radial-gradient(circle at 73% 77%, rgba(205, 205, 205,0.03) 0%, rgba(205, 205, 205,0.03) 18%,transparent 18%, transparent 100%),radial-gradient(circle at 57% 51%, rgba(161, 161, 161,0.03) 0%, rgba(161, 161, 161,0.03) 64%,transparent 64%, transparent 100%),radial-gradient(circle at 40% 84%, rgba(115, 115, 115,0.03) 0%, rgba(115, 115, 115,0.03) 14%,transparent 14%, transparent 100%),linear-gradient(90deg, rgb(0,0,0),rgb(0,0,0))`,
        }}
      >
        <CustomTypography
          width="100%"
          component="h1"
          sx={{
            color: 'white',
            fontSize: '3rem',
            textAlign: 'center',
            '&:hover': {
              cursor: 'pointer',
            },
          }}
          onClick={() => router.push('/')}
        >
          big-AGI
        </CustomTypography>
        <CustomTypography level="h3" component="h1" mb={4} sx={{ fontWeight: 'bold' }}>
          Terms of Service
        </CustomTypography>

        <CustomTypography level="body-lg" mb={2}>
          Last Updated: 1/24/2024
        </CustomTypography>

        <CustomTypography level="body-lg" mb={2}>
          Welcome to bigAGI! By accessing or using our chatbot application, you agree to be bound by these Terms of Service. If you disagree with any part of
          the terms, you may not access the service.
        </CustomTypography>

        <CustomTypography level="h4" component="h2" mb={2} sx={{ fontWeight: 'bold' }}>
          1. Use of Our Service
        </CustomTypography>
        <CustomTypography level="body-md" mb={2}>
          bigAGI provides a chatbot service. Users are responsible for the information they input into bigAGI. We do not endorse or assume any responsibility
          for the content generated by the chatbot.
        </CustomTypography>

        <CustomTypography level="h4" component="h2" mb={2} sx={{ fontWeight: 'bold' }}>
          2. Content
        </CustomTypography>
        <CustomTypography level="body-md" mb={2}>
          You understand that all information, whether publicly posted or privately transmitted through bigAGI, is the sole responsibility of the person from
          whom such content originated. We do not control the content passed through the chatbot and, as such, do not guarantee the accuracy, integrity, or
          quality of such content.
        </CustomTypography>

        <CustomTypography level="h4" component="h2" mb={2} sx={{ fontWeight: 'bold' }}>
          3. Limitation of Liability
        </CustomTypography>
        <CustomTypography level="body-md" mb={2}>
          bigAGI shall not be liable for any statements or conduct of any third party using the service. You agree that your use of the chatbot is at your sole
          risk and that bigAGI is not liable for any content generated, including but not limited to errors, defamatory statements, or other types of content.
        </CustomTypography>

        <CustomTypography level="h4" component="h2" mb={2} sx={{ fontWeight: 'bold' }}>
          4. Modifications to Service
        </CustomTypography>
        <CustomTypography level="body-md" mb={2}>
          bigAGI reserves the right to modify or discontinue, temporarily or permanently, the service with or without notice. You agree that bigAGI shall not be
          liable to you or to any third party for any modification, suspension, or discontinuance of the service.
        </CustomTypography>

        <CustomTypography level="h4" component="h2" mb={2} sx={{ fontWeight: 'bold' }}>
          5. General Conditions
        </CustomTypography>
        <CustomTypography level="body-md" mb={4}>
          We reserve the right to update and change the Terms of Service from time to time without notice. Your continued use of the service after any such
          changes shall constitute your consent to such changes.
        </CustomTypography>

        <CustomTypography level="body-md" mb={2}>
          For any questions or inquiries regarding the Terms of Service, please contact us.
        </CustomTypography>

        <CustomTypography level="body-md" mb={2}>
          This document was last updated on 1/24/2024.
        </CustomTypography>
      </Box>
    </CssVarsProvider>
  );
}
