/**
 * LLMs Defs Manifest - declares which source files carry each vendor's model definitions.
 *
 * This drives the per-vendor model-defs versions in `gen/llms.defs.versions.ts` (generated by
 * `tools/develop/gen-llms-defs/generate-llms-defs.mjs`, invoked automatically by `next dev`
 * and `next build`): when a claimed file changes in runtime-semantic terms (comments,
 * formatting and type-only edits are normalized away), that bucket's version rolls, and
 * clients selectively re-list only the affected services on their next boot.
 *
 * Buckets:
 * - one per ModelVendorId (`satisfies` makes vendor add/remove a compile error here)
 * - `_shared`: files shaping every vendor's output; rolling it refreshes all services
 * - `_openaiCompat`: the OpenAI-lookalike sub-parsers (host-heuristic gateways such as
 *   Fireworks, Novita, ChutesAI) plus the first-party OpenAI table (proxies); custom-host
 *   OpenAI services compare against this bucket instead of `openai`
 *
 * Entry fields:
 * - `files`: paths relative to `src/modules/llms/server/`; a file may be claimed by multiple
 *   buckets when its definitions feed several surfaces (e.g. openai.models.ts also feeds
 *   azure and the openrouter parameter inheritance)
 * - `epoch`: optional editorial lever - bump it to force-roll the bucket without touching
 *   definitions (comment edits no longer roll versions, this is the sanctioned way)
 * - `ignoreImports`: value-imports of claimed files deliberately NOT folded into this
 *   bucket's version (the generator's import audit fails on unclaimed imports otherwise)
 */

import type { ModelVendorId } from '../vendors/vendors.registry';


export interface LlmsDefsManifestEntry {
  readonly files: readonly string[];
  readonly epoch?: number;
  readonly ignoreImports?: readonly string[];
}

export type LlmsDefsBucketId = ModelVendorId | '_shared' | '_openaiCompat';


export const LLMS_DEFS_MANIFEST = {

  alibaba: { files: ['openai/models/alibaba.models.ts'] },
  anthropic: { files: ['anthropic/anthropic.models.ts'] },
  // azure resolves deployments against the openai curated table (llmsFallbackForOpenAIModel)
  azure: { files: ['openai/models/azure.models.ts', 'openai/models/openai.models.ts'] },
  // bedrock mantles the anthropic curated models (llmBedrockFindAnthropicModel)
  bedrock: { files: ['bedrock/bedrock.models.ts', 'anthropic/anthropic.models.ts'] },
  cerebras: { files: ['openai/models/cerebras.models.ts', 'openai/wiretypes/cerebras.wiretypes.ts'] },
  cohere: { files: ['openai/models/cohere.models.ts'] },
  deepseek: { files: ['openai/models/deepseek.models.ts'] },
  googleai: { files: ['gemini/gemini.models.ts'] },
  groq: { files: ['openai/models/groq.models.ts', 'openai/wiretypes/groq.wiretypes.ts'] },
  llmman: { files: ['openai/models/llmman.models.ts'] },
  lmstudio: { files: ['openai/models/lmstudio.models.ts'] },
  localai: { files: ['openai/models/localai.models.ts'] },
  mistral: { files: ['openai/models/mistral.models.ts'] },
  modular: { files: ['openai/models/modular.models.ts'] },
  moonshot: { files: ['openai/models/moonshot.models.ts'] },
  nvidianim: { files: ['openai/models/nvidianim.models.ts'] },
  // ollama.wiretypes parses the local server's list response (used by the dispatch)
  ollama: { files: ['ollama/ollama.models.ts', 'ollama/ollama.wiretypes.ts'] },
  openai: { files: ['openai/models/openai.models.ts'] },
  // openrouter inherits per-creator parameters from the first-party curated tables (llmOrt*Lookup)
  openrouter: {
    files: [
      'openai/models/openrouter.models.ts',
      'openai/wiretypes/openrouter.wiretypes.ts',
      'anthropic/anthropic.models.ts',
      'gemini/gemini.models.ts',
      'openai/models/moonshot.models.ts',
      'openai/models/openai.models.ts',
      'openai/models/sakanaai.models.ts',
      'openai/models/xai.models.ts',
      'openai/models/zai.models.ts',
    ],
  },
  perplexity: { files: ['openai/models/perplexity.models.ts'] },
  sakanaai: { files: ['openai/models/sakanaai.models.ts'] },
  togetherai: { files: ['openai/models/together.models.ts', 'openai/wiretypes/togetherai.wiretypes.ts'] },
  xai: { files: ['openai/models/xai.models.ts'] },
  zai: { files: ['openai/models/zai.models.ts'] },

} as const satisfies Record<ModelVendorId, LlmsDefsManifestEntry>;


// noinspection JSUnusedGlobalSymbols - this is actually used, but imported using the transpiler into generate-llms-defs.mjs
export const LLMS_DEFS_EXTRA_BUCKETS = {

  // Files that shape the output of every vendor: rolling this refreshes all services.
  // NOTE: listModels.dispatch.ts is the composition root (imports all parsers) and is
  // exempted from the import audit by the generator.
  _shared: {
    files: [
      'models.mappings.ts',
      'llm.server.variants.ts',
      'llm.server.types.ts',
      'listModels.dispatch.ts',
    ],
  },

  // OpenAI-lookalike gateways, selected by host heuristics under the 'openai' dialect.
  // Custom-host OpenAI services (non api.openai.com) compare against this bucket.
  // tlusapi is structure-detected across all OpenAI-compatible dialects but only ever
  // triggers on custom gateways, so it lives here.
  // openai.models.ts is claimed too: proxies to OpenAI (LiteLLM, gateways) sit behind a
  // custom host but are parsed by the first-party parser, so its edits must reach them.
  // openrouter.models.ts is claimed for the Nous Research mapper reuse; its other
  // first-party lookup imports (anthropic/gemini/moonshot/sakanaai/xai/zai) are deliberately
  // untracked here (owner decision: lookalike hosts do not roll on those - bump `epoch` for a roll).
  _openaiCompat: {
    files: [
      'openai/models/arceeai.models.ts',
      'openai/models/baseten.models.ts',
      'openai/models/chutesai.models.ts',
      'openai/models/fastapi.models.ts',
      'openai/models/fireworksai.models.ts',
      'openai/models/llmapi.models.ts',
      'openai/models/minimax.models.ts',
      'openai/models/nousresearch.models.ts',
      'openai/models/novita.models.ts',
      'openai/models/nvidianim.models.ts',
      'openai/models/openai.models.ts',
      'openai/models/openrouter.models.ts',
      'openai/models/tlusapi.models.ts',
      'openai/wiretypes/baseten.wiretypes.ts',
      'openai/wiretypes/fireworksai.wiretypes.ts',
      'openai/wiretypes/llmapi.wiretypes.ts',
      'openai/wiretypes/novita.wiretypes.ts',
      'openai/wiretypes/openrouter.wiretypes.ts',
    ],
    ignoreImports: [
      'anthropic/anthropic.models.ts',
      'gemini/gemini.models.ts',
      'openai/models/moonshot.models.ts',
      'openai/models/sakanaai.models.ts',
      'openai/models/xai.models.ts',
      'openai/models/zai.models.ts',
    ],
  },

} as const satisfies Record<'_shared' | '_openaiCompat', LlmsDefsManifestEntry>;
